name: deployment_local
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - click
  - pytorch-pretrained-bert=0.6.2
  - lmdb=0.94
  - tensorboardX=1.2
  - tensorpack=0.9.4
  - tqdm=4.31.1
  - easydict=1.9
  - PyYAML=5.1.2
  - jsonlines=1.2.0
  - json-lines=0.5.0
  - matplotlib
  - Cython
  - python-prctl
  - msgpack
  - msgpack-numpy
  - gensim
  - torch=1.3.1
  - torchvision=0.4.2
  - numpy=1.16.4
  - pandas
  - python-magic
  - requests
    pip:
      - tensorflow==1.13.1


