apiVersion: batch/v1
kind: Job
metadata:
  name: vilbert-job-0.1.dev10-g7158c0c.d20200127181343
  namespace: human-ai-dialog
  annotations:
    author-name: "Maryam Ziaeefard"
    author-email: "maryam.ziaeefard.e@thalesdigital.io"
spec:
  ttlSecondsAfterFinished: 172800
  backoffLimit: 1
  template:
    spec:
      imagePullSecrets:
      - name: human-ai-dialog-collaborative-docker-registry-secret
      initContainers:
      - name: init-output-folder
        image: busybox
        command: ["mkdir","-p","/nas-data/outputs/vilbert-job-0.1.dev10-g7158c0c.d20200127181343"]
        volumeMounts:
        - name: nas-data-volume
          mountPath: /nas-data
      containers:
      - name: vilbert-pod
        image: "collaborative-docker-registry.collaborative.local:5100/ca.thalesgroup.trt/human-ai-dialog/vilbert:0.1.dev10-g7158c0c.d20200127181343"
        command: ["/bin/sh","-c"]
        args: ["cd vilbert && python convert_trainval_lmdb.py --input-dir=/nas-data/vilbert/data2/ --output-dir=/nas-data/outputs/vilbert-job-0.1.dev10-g7158c0c.d20200127181343"]
        env: 
          - name: LC_ALL
            value: C.UTF-8
          - name: LANG
            value: C.UTF-8
        volumeMounts:
          - name: nas-data-volume
            mountPath: /nas-data
      restartPolicy: Never    
      volumes:
      # Mount SAMBA volume from common-nas-server.common.local
      - name: nas-data-volume
        flexVolume:
          driver: "fstab/cifs"
          fsType: "cifs"
          secretRef:
            name: "human-ai-dialog-cifs-service-user-secret"
          options:
            networkPath: "//common-nas-server.common.local/HUMAN_AI_DIALOG_SHARED"
            mountOptions: "dir_mode=0755,file_mode=0644,noperm,vers=3.0,iocharset=utf8"
